### ISSUE TITLE
jQuery 3: error 'url.indexOf is not a function'

### ISSUE THREAD

**Issue by JamesMcMahon** [vodkabears/Vide#183]
Getting an error when using Vide with JQuery 3.0.0.

Here is the no-minified stacktrace:

```
jQuery.Deferred exception: url.indexOf is not a function TypeError: url.indexOf is not a function
    at jQuery.fn.load (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.js:9612:13)
    at findPoster (file:///Users/j/temp/test-site/js/jquery.vide.js:175:39)
    at Vide.init (file:///Users/j/temp/test-site/js/jquery.vide.js:280:7)
    at new Vide (file:///Users/j/temp/test-site/js/jquery.vide.js:219:12)
    at HTMLBodyElement.<anonymous> (file:///Users/j/temp/test-site/js/jquery.vide.js:461:18)
    at Function.each (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.js:359:19)
    at jQuery.each (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.js:152:17)
    at jQuery.$.fn.(anonymous function) [as vide] (file:///Users/j/temp/test-site/js/jquery.vide.js:454:10)
    at HTMLBodyElement.<anonymous> (file:///Users/j/temp/test-site/js/jquery.vide.js:497:28)
    at Function.each (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.js:359:19) undefined
```

I was looking at it in the Chrome debugger it looks like the string being passed to `$` in this line:

``` javascript
$('<img src="' + path + '.gif">').load(onLoad);
```

Is getting coerced into a function, which doesn't have an `indexOf` function. Which blows up when it hits the first line in load.

``` javascript
jQuery.fn.load = function( url, params, callback ) {
    var selector, type, response,
        self = this,
        off = url.indexOf( " " );
```

**Comment by JamesMcMahon** [comment]
Ah, looks like `load` is deprecated in jQuery 3.

From https://blog.jquery.com/2015/07/13/jquery-3-0-and-jquery-compat-3-0-alpha-versions-released/:
> Removed deprecated event aliases

>.load, .unload, and .error, deprecated since jQuery 1.8, are no more. Use .on() to register listeners.

**Comment by JamesMcMahon** [comment]
Submitted a pull request with a fix.

**Comment by nwaxiomatic** [comment]
This has not been fixed in the bower version

**Comment by TobiasMalikowski** [comment]
+1, has not been fixed in the bower version

**Comment by skji** [comment]
+2, has not been fixed in the bower version

**Comment by santarinto** [comment]
has not been fixed in v. 3.1.0

**Comment by Undefitied** [comment]
has not been fixed in v. 3.1.0 +

**Comment by pheliperocha** [comment]
has not been fixed in v. 3.1.0 ++

**Comment by niwann** [comment]
has not been fixed in v. 3.1.0 ++

**Comment by jamesfawcett** [comment]
Still not fixed in bower version 3.1.0.  v3.0.1 direct from vendor website working perfectly https://unpkg.com/isotope-layout@3.0.1/dist/isotope.pkgd.min.js

**Comment by xTITTANx** [comment]
has not been fixed in v. 3.1.1 ++

**Comment by bke-daniel** [comment]
Still not fixed in the Bower Version

**Comment by kinotto** [comment]
still not fixed in v. 3.2.1

**Comment by MALIK-0** [comment]
Can someone reopen this? I'll think this will never get solved if the issue is marked as closed ...

**Comment by mjavo** [comment]
```
//This line fails with uncaught error [Uncaught TypeError: 
//type.indexOf is not a function] in v. 3.1.1 
//--- Going to modify to test for function first before invoking.
// It is found in the **trigger function** definition block

if ( type.indexOf( "." ) > -1 ) { 
     // Namespaced trigger; create a regexp to match event type in handle()
	namespaces = type.split( "." );
	type = namespaces.shift();
	namespaces.sort();
}
 ontype = type.indexOf( ":" ) < 0 && "on" + type;
```

Edit to add: Resolved the issue with that particular section. Patched files attached [zip].
```
//modify to add in the preceding variable declaration block of **trigger function**:
// isfunc = (typeof type.indexOf == "function"); 
//use as follows
	
if (isfunc && type.indexOf(".") > -1) {
    // Namespaced trigger; create a regexp to match event type in handle()
       namespaces = type.split( "." );
       type = namespaces.shift();
       namespaces.sort();
}
ontype = isfunc && type.indexOf(":") < 0 && "on" + type;


//Note: ALSO edited the minified version.
```
[jquery-3.1.1-patched.zip](https://github.com/vodkabears/Vide/files/1106859/jquery-3.1.1-patched.zip)

**Comment by shorif2000** [comment]
3.2.1 is not fixed

**Comment by sheptang** [comment]
has not been fixed in v. 3.2.1

**Comment by latimercaleb** [comment]
Came here because of load() issues to learn that there is an issue that is not fixed. Time 12:10AM EST 10/25/2017

**Comment by artkrv** [comment]
Just modify the end of fakeloader.min.js as folow:
`this.css({ backgroundColor: d.bgColor, zIndex: d.zIndex }) }, function () { } }(jQuery);`

**Comment by bohdan-vorona** [comment]
**Better approach may be a polyfill like this**

`jQuery.fn.load = function(callback) { 
    $(window).on("load", callback) 
};`

**Comment by mdrzn** [comment]
jQuery.Load() was so easy to use and with lots of tutorials online, now I can't find how to use jQuery.on() because the official FAQ is a mess, and all the google results brings up ".load" which is deprecated.
Great.

**Comment by quangnx** [comment]
still in strouble

**Comment by shorif2000** [comment]
not fixed in npm 3.2.1

**Comment by shorif2000** [comment]
> **Better approach may be a polyfill like this**
> 
> `jQuery.fn.load = function(callback) { $(window).on("load", callback) };`

I added it like this in my `App.js` but it only shows `Downloading resources:`

```
const jQuery = require("jquery");
// this step is important, or else bootstrap will throw an error
window.jQuery = window.$ = jQuery; // This only needs to be imported once in your app
jQuery.fn.load = function(callback) { $(window).on("load", callback) };
```

**Comment by besanh** [comment]
3.5.1 still not fixed
